// Copyright (c) 2026 Kim Ommundsen. Licensed under the MPL-2.0.
// See LICENSE.txt in the project root or https://mozilla.org/MPL/2.0/

using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace Conjecture.Core.Internal;

internal static class ReproFileBuilder
{
    private static readonly Dictionary<Type, string> TypeAliases = new()
    {
        [typeof(int)] = "int",
        [typeof(bool)] = "bool",
        [typeof(double)] = "double",
        [typeof(float)] = "float",
        [typeof(string)] = "string",
        [typeof(byte[])] = "byte[]",
        [typeof(long)] = "long",
        [typeof(short)] = "short",
        [typeof(uint)] = "uint",
        [typeof(ulong)] = "ulong",
        [typeof(char)] = "char",
        [typeof(decimal)] = "decimal",
        [typeof(object)] = "object",
    };

    private static string GetTypeName(Type type)
    {
        if (TypeAliases.TryGetValue(type, out string? alias))
        {
            return alias;
        }

        if (type.IsArray)
        {
            return $"{GetTypeName(type.GetElementType()!)}[]";
        }

        Type? nullableUnderlying = Nullable.GetUnderlyingType(type);
        if (nullableUnderlying is not null)
        {
            return $"{GetTypeName(nullableUnderlying)}?";
        }

        if (!type.IsGenericType)
        {
            return type.Name;
        }

        string baseName = type.Name[..type.Name.IndexOf('`')];
        string args = string.Join(", ", type.GetGenericArguments().Select(GetTypeName));
        return $"{baseName}<{args}>";
    }

    private static string RenderValue(object? value, Type type)
    {
        if (value is null)
        {
            return $"({GetTypeName(type)})null!";
        }

        Func<object, string>? formatter = FormatterRegistry.GetUntyped(type);
        return formatter is not null ? formatter(value) : value.ToString() ?? "null";
    }

    private static string GetFrameworkUsing(TestFramework framework)
    {
        return framework switch
        {
            TestFramework.NUnit => "using NUnit.Framework;",
            TestFramework.MSTest => "using Microsoft.VisualStudio.TestTools.UnitTesting;",
            _ => "using Xunit;",
        };
    }

    private static string GetTestAttribute(TestFramework framework)
    {
        return framework switch
        {
            TestFramework.NUnit => "[Test]",
            TestFramework.MSTest => "[TestMethod]",
            _ => "[Fact]",
        };
    }

    internal static void WriteToFile(ReproContext context, string outputPath)
    {
        try
        {
            Directory.CreateDirectory(outputPath);
            string timestamp = context.GeneratedAt.ToString("yyyyMMddHHmmss");
            string fileName = $"{context.TestClassName}_{context.MethodName}_{timestamp}.cs";
            string fullPath = Path.Combine(outputPath, fileName);
            string content = Build(context);
            File.WriteAllText(fullPath, content);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }

    internal static string Build(ReproContext context)
    {
        StringBuilder sb = new();

        string os = RuntimeInformation.OSDescription;
        string dotnet = Environment.Version.ToString();
        string arch = RuntimeInformation.ProcessArchitecture.ToString();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated: {context.GeneratedAt:O}");
        sb.AppendLine($"// Seed: 0x{context.Seed:X}");
        sb.AppendLine($"// OS: {os}");
        sb.AppendLine($"// .NET: {dotnet}");
        sb.AppendLine($"// Arch: {arch}");
        sb.AppendLine();
        sb.AppendLine(GetFrameworkUsing(context.Framework));
        sb.AppendLine();
        sb.AppendLine($"[Property(Seed = 0x{context.Seed:X})]");
        sb.AppendLine(GetTestAttribute(context.Framework));

        List<(string Name, object? Value, Type Type)> paramList = [.. context.Parameters];

        if (context.IsAsync)
        {
            sb.AppendLine("public async Task Counterexample()");
        }
        else
        {
            sb.AppendLine("public void Counterexample()");
        }

        sb.AppendLine("{");

        foreach ((string name, object? value, Type type) in paramList)
        {
            string typeName = GetTypeName(type);
            string rendered = RenderValue(value, type);
            sb.AppendLine($"    {typeName} {name} = {rendered};");
        }

        string paramNames = string.Join(", ", paramList.Select(static p => p.Name));
        string call = $"new {context.TestClassName}().{context.MethodName}({paramNames})";

        if (context.IsAsync)
        {
            sb.AppendLine($"    await {call};");
        }
        else
        {
            sb.AppendLine($"    {call};");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}