// Copyright (c) 2026 Kim Ommundsen. Licensed under the MPL-2.0.
// See LICENSE.txt in the project root or https://mozilla.org/MPL/2.0/

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Conjecture.Generators;

/// <summary>Incremental source generator that emits <c>GenForRegistry.g.cs</c> — a <c>[ModuleInitializer]</c> that registers <c>IStrategyProvider</c> factories for all <c>[Arbitrary]</c> types, enabling <c>Generate.For&lt;T&gt;()</c>.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class GenForGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> types = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Conjecture.Core.ArbitraryAttribute",
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Where(static symbol => !symbol.IsAbstract && !ImplementsStrategyProvider(symbol));

        IncrementalValueProvider<ImmutableDictionary<string, string>> registry =
            context.CompilationProvider.Select(static (compilation, _) => ProviderRegistry.Build(compilation));

        IncrementalValuesProvider<(INamedTypeSymbol Symbol, ImmutableDictionary<string, string> Registry)> combined =
            types.Combine(registry);

        IncrementalValueProvider<ImmutableArray<(INamedTypeSymbol Symbol, ImmutableDictionary<string, string> Registry)>> collected =
            combined.Collect();

        context.RegisterSourceOutput(collected, static (ctx, items) =>
        {
            List<(string TypeFqn, string ProviderFqn)> entries = [];
            foreach ((INamedTypeSymbol symbol, ImmutableDictionary<string, string> reg) in items)
            {
                string typeFqn = symbol.ToDisplayString(TypeModelExtractor.TypeNameFormat);
                if (reg.TryGetValue(typeFqn, out string? knownProvider))
                {
                    entries.Add((typeFqn, knownProvider));
                }
                else
                {
                    (TypeModel? model, ImmutableArray<Diagnostic> diagnostics) = TypeModelExtractor.Extract(symbol, reg);
                    bool hasError = false;
                    foreach (Diagnostic d in diagnostics)
                    {
                        if (d.Severity == DiagnosticSeverity.Error)
                        {
                            hasError = true;
                        }
                    }

                    if (!hasError && model is not null)
                    {
                        entries.Add((typeFqn, typeFqn + "Arbitrary"));
                    }
                }
            }

            if (entries.Count == 0)
            {
                return;
            }

            string source = EmitRegistry(entries);
            ctx.AddSource("GenForRegistry.g.cs", source);
        });
    }

    private static bool ImplementsStrategyProvider(INamedTypeSymbol symbol)
    {
        foreach (INamedTypeSymbol iface in symbol.AllInterfaces)
        {
            if (iface.Name == "IStrategyProvider" &&
                iface.ContainingNamespace is { Name: "Core", ContainingNamespace.Name: "Conjecture" } ns &&
                ns.ContainingNamespace.ContainingNamespace.IsGlobalNamespace)
            {
                return true;
            }
        }

        return false;
    }

    private static string EmitRegistry(List<(string TypeFqn, string ProviderFqn)> entries)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Copyright (c) 2026 Kim Ommundsen. Licensed under the MPL-2.0.");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Conjecture.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class GenForRegistryInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        foreach ((string typeFqn, string providerFqn) in entries)
        {
            sb.AppendLine($"        global::Conjecture.Core.GenForRegistry.Register(");
            sb.AppendLine($"            typeof(global::{typeFqn}),");
            sb.AppendLine($"            static () => new global::{providerFqn}());");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
