// Copyright (c) 2026 Kim Ommundsen. Licensed under the MPL-2.0.
// See LICENSE.txt in the project root or https://mozilla.org/MPL/2.0/

using System.Text;

namespace Conjecture.Generators;

internal static class HierarchyStrategyEmitter
{
    internal static string Emit(HierarchyTypeModel model)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine("namespace " + model.Namespace + ";");
            sb.AppendLine();
        }

        string fqn = model.FullyQualifiedName;
        string className = model.TypeName + "Arbitrary";

        sb.AppendLine("internal sealed class " + className + " : global::Conjecture.Core.IStrategyProvider<" + fqn + ">");
        sb.AppendLine("{");
        sb.AppendLine("    public global::Conjecture.Core.Strategy<" + fqn + "> Create()");
        sb.AppendLine("    {");
        sb.AppendLine("        global::Conjecture.Core.IStrategyProvider<" + fqn + ">[] providers =");
        sb.AppendLine("        [");

        for (int i = 0; i < model.Subtypes.Length; i++)
        {
            string providerTypeName = model.Subtypes[i].ProviderTypeName;
            bool isLast = i == model.Subtypes.Length - 1;
            string suffix = isLast ? "" : ",";
            sb.AppendLine("            new " + providerTypeName + "()" + suffix);
        }

        sb.AppendLine("        ];");
        sb.AppendLine("        global::Conjecture.Core.Strategy<" + fqn + ">[] strategies = new global::Conjecture.Core.Strategy<" + fqn + ">[providers.Length];");
        sb.AppendLine("        for (int i = 0; i < providers.Length; i++) { strategies[i] = providers[i].Create(); }");
        sb.AppendLine("        return global::Conjecture.Core.Generate.OneOf(strategies);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
