// Copyright (c) 2026 Kim Ommundsen. Licensed under the MPL-2.0.
// See LICENSE.txt in the project root or https://mozilla.org/MPL/2.0/

using System.Text;

namespace Conjecture.Generators;

internal static class HierarchyStrategyEmitter
{
    internal static string Emit(HierarchyTypeModel model)
    {
        if (model.Subtypes.IsEmpty)
        {
            throw new ArgumentException("Cannot emit a hierarchy strategy with no subtypes.", nameof(model));
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Conjecture.Core;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine("namespace " + model.Namespace + ";");
            sb.AppendLine();
        }

        string fqn = model.FullyQualifiedName;
        string typeParamsJoined = string.Join(", ", model.TypeParameters);
        string typeArgsSuffix = model.TypeParameters.IsEmpty ? "" : "<" + typeParamsJoined + ">";
        string classNameWithTypeParams = model.TypeName + "Arbitrary" + typeArgsSuffix;
        string interfaceType = "global::Conjecture.Core.IStrategyProvider<global::" + fqn + ">";

        sb.AppendLine("internal sealed class " + classNameWithTypeParams + " : " + interfaceType);
        sb.AppendLine("{");
        sb.AppendLine("    public global::Conjecture.Core.Strategy<global::" + fqn + "> GetStrategy() =>");
        sb.AppendLine("        global::Conjecture.Core.Generate.OneOf(");

        for (int i = 0; i < model.Subtypes.Length; i++)
        {
            string providerTypeName = model.Subtypes[i].ProviderTypeName + typeArgsSuffix;
            bool isLast = i == model.Subtypes.Length - 1;
            string suffix = isLast ? "" : ",";
            sb.AppendLine("            new " + providerTypeName + "().GetStrategy()");
            sb.AppendLine("                .Select(static x => (global::" + fqn + ")x)" + suffix);
        }

        sb.AppendLine("        );");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
