// Copyright (c) 2026 Kim Ommundsen. Licensed under the MPL-2.0.
// See LICENSE.txt in the project root or https://mozilla.org/MPL/2.0/

using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Conjecture.Generators;

internal static class StrategyEmitter
{
    private static readonly Dictionary<string, (string GenExpr, string ShortName)> PrimitiveData = new()
    {
        ["System.Int32"] = ("global::Conjecture.Core.Generate.Integers<int>()", "int"),
        ["System.Int64"] = ("global::Conjecture.Core.Generate.Integers<long>()", "long"),
        ["System.Byte"] = ("global::Conjecture.Core.Generate.Integers<byte>()", "byte"),
        ["System.Boolean"] = ("global::Conjecture.Core.Generate.Booleans()", "bool"),
        ["System.String"] = ("global::Conjecture.Core.Generate.Strings()", "string"),
        ["System.Double"] = ("global::Conjecture.Core.Generate.Doubles()", "double"),
        ["System.Single"] = ("global::Conjecture.Core.Generate.Floats()", "float"),
        ["System.Decimal"] = ("global::Conjecture.Core.Generate.Decimals()", "decimal"),
        ["System.Char"] = ("global::Conjecture.Core.Generate.Chars()", "char"),
        ["System.Guid"] = ("global::Conjecture.Core.Generate.Guids()", "global::System.Guid"),
        ["System.DateTime"] = ("global::Conjecture.Core.Generate.DateTimes()", "global::System.DateTime"),
        ["System.DateTimeOffset"] = ("global::Conjecture.Core.Generate.DateTimeOffsets()", "global::System.DateTimeOffset"),
        ["System.DateOnly"] = ("global::Conjecture.Core.Generate.DateOnlyValues()", "global::System.DateOnly"),
        ["System.TimeOnly"] = ("global::Conjecture.Core.Generate.TimeOnlyValues()", "global::System.TimeOnly"),
        ["System.TimeSpan"] = ("global::Conjecture.Core.Generate.TimeSpans()", "global::System.TimeSpan"),
        ["System.UInt32"] = ("global::Conjecture.Core.Generate.Integers<uint>()", "uint"),
        ["System.UInt64"] = ("global::Conjecture.Core.Generate.Integers<ulong>()", "ulong"),
        ["System.Int16"] = ("global::Conjecture.Core.Generate.Integers<short>()", "short"),
        ["System.UInt16"] = ("global::Conjecture.Core.Generate.Integers<ushort>()", "ushort"),
        ["System.SByte"] = ("global::Conjecture.Core.Generate.Integers<sbyte>()", "sbyte"),
    };

    internal static string Emit(TypeModel model)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine("namespace " + model.Namespace + ";");
            sb.AppendLine();
        }

        string fqn = model.FullyQualifiedName;
        string className = model.TypeName + "Arbitrary";

        sb.AppendLine("internal sealed class " + className + " : global::Conjecture.Core.IStrategyProvider<" + fqn + ">");
        sb.AppendLine("{");

        bool isPartialCtor = model.ConstructionMode == ConstructionMode.PartialConstructor;
        string fieldVisibility = isPartialCtor ? "internal" : "private";

        if (!model.Members.IsEmpty)
        {
            for (int i = 0; i < model.Members.Length; i++)
            {
                MemberModel member = model.Members[i];
                sb.AppendLine("    " + fieldVisibility + " static readonly global::Conjecture.Core.Strategy<" + ResolveStrategyType(member) + "> _s" + i + " = " + ResolveGenExpr(member) + ";");
            }
            sb.AppendLine();
        }

        if (isPartialCtor)
        {
            sb.AppendLine("    public global::Conjecture.Core.Strategy<" + fqn + "> Create()");
            sb.AppendLine("    {");
            sb.AppendLine("        return global::Conjecture.Core.Generate.Compose<" + fqn + ">(ctx =>");
            sb.AppendLine("        {");
            sb.AppendLine("            using global::System.IDisposable _scope = global::Conjecture.Core.PartialConstructorContext.Use(ctx);");
            sb.AppendLine("            return new " + fqn + "();");
            sb.AppendLine("        });");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine("    public global::Conjecture.Core.Strategy<" + fqn + "> Create() =>");

            if (model.Members.IsEmpty)
            {
                sb.AppendLine("        global::Conjecture.Core.Generate.Compose<" + fqn + ">(_ => new " + fqn + "());");
            }
            else if (model.ConstructionMode == ConstructionMode.ObjectInitializer)
            {
                sb.AppendLine("        global::Conjecture.Core.Generate.Compose<" + fqn + ">(ctx => new " + fqn + " {");

                for (int i = 0; i < model.Members.Length; i++)
                {
                    MemberModel member = model.Members[i];
                    bool isLast = i == model.Members.Length - 1;
                    string suffix = isLast ? " });" : ",";
                    sb.AppendLine("            " + member.Name + " = ctx.Generate(_s" + i + ")" + suffix);
                }
            }
            else
            {
                sb.AppendLine("        global::Conjecture.Core.Generate.Compose<" + fqn + ">(ctx => new " + fqn + "(");

                for (int i = 0; i < model.Members.Length; i++)
                {
                    bool isLast = i == model.Members.Length - 1;
                    string suffix = isLast ? "));" : ",";
                    sb.AppendLine("            ctx.Generate(_s" + i + ")" + suffix);
                }
            }

        }

        sb.AppendLine("}");

        if (isPartialCtor && !model.Members.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine("partial class " + model.TypeName);
            sb.AppendLine("{");
            sb.AppendLine("    public partial " + model.TypeName + "()");
            sb.AppendLine("    {");

            for (int i = 0; i < model.Members.Length; i++)
            {
                MemberModel member = model.Members[i];
                sb.AppendLine("        " + member.Name + " = global::Conjecture.Core.PartialConstructorContext.Current.Generate(" + className + "._s" + i + ");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    internal static string ResolveStrategyType(MemberModel member) => member.Kind switch
    {
        MemberGenerationKind.Primitive =>
            PrimitiveData.TryGetValue(member.TypeFullName, out (string GenExpr, string ShortName) p) ? p.ShortName : "/* unsupported */",
        MemberGenerationKind.Enum =>
            "global::" + member.TypeFullName,
        MemberGenerationKind.NullableValue =>
            PrimitiveData.TryGetValue(member.AuxiliaryTypeName, out (string GenExpr, string ShortName) n) ? n.ShortName + "?" : "/* unsupported */",
        MemberGenerationKind.List =>
            PrimitiveData.TryGetValue(member.AuxiliaryTypeName, out (string GenExpr, string ShortName) l)
                ? "global::System.Collections.Generic.List<" + l.ShortName + ">"
                : "/* unsupported */",
        MemberGenerationKind.Dictionary =>
            BuildDictionaryStrategyType(member.AuxiliaryTypeName),
        MemberGenerationKind.ImmutableArray =>
            PrimitiveData.TryGetValue(member.AuxiliaryTypeName, out (string GenExpr, string ShortName) ia)
                ? "global::System.Collections.Immutable.ImmutableArray<" + ia.ShortName + ">"
                : "/* unsupported */",
        MemberGenerationKind.Set =>
            PrimitiveData.TryGetValue(member.AuxiliaryTypeName, out (string GenExpr, string ShortName) s)
                ? "global::System.Collections.Generic.IReadOnlySet<" + s.ShortName + ">"
                : "/* unsupported */",
        MemberGenerationKind.ValueTuple =>
            BuildValueTupleStrategyType(member.AuxiliaryTypeName),
        MemberGenerationKind.ArbitraryReference =>
            "global::" + member.TypeFullName,
        MemberGenerationKind.ExternalStrategyProvider =>
            "global::" + member.TypeFullName,
        _ =>
            "/* unsupported */",
    };

    internal static string ResolveGenExpr(MemberModel member)
    {
        return member.Kind switch
        {
            MemberGenerationKind.Enum =>
                "global::Conjecture.Core.Generate.Enums<global::" + member.TypeFullName + ">()",
            MemberGenerationKind.NullableValue =>
                PrimitiveData.TryGetValue(member.AuxiliaryTypeName, out (string GenExpr, string ShortName) nv)
                    ? "global::Conjecture.Core.Generate.Nullable<" + nv.ShortName + ">(" + nv.GenExpr + ")"
                    : $"/* unsupported nullable inner type: {member.AuxiliaryTypeName} */",
            MemberGenerationKind.List =>
                BuildWrappedExpr(member.AuxiliaryTypeName, "Lists"),
            MemberGenerationKind.Dictionary =>
                BuildDictionaryGenExpr(member.AuxiliaryTypeName),
            MemberGenerationKind.ImmutableArray =>
                BuildWrappedExpr(member.AuxiliaryTypeName, "Lists") + ".Select(global::System.Collections.Immutable.ImmutableArray.CreateRange)",
            MemberGenerationKind.Set =>
                BuildWrappedExpr(member.AuxiliaryTypeName, "Sets"),
            MemberGenerationKind.ValueTuple =>
                BuildValueTupleGenExpr(member.AuxiliaryTypeName),
            MemberGenerationKind.ArbitraryReference =>
                "new global::" + member.TypeFullName + "Arbitrary().Create()",
            MemberGenerationKind.ExternalStrategyProvider =>
                "((global::Conjecture.Core.IStrategyProvider<global::" + member.TypeFullName + ">)new global::" + member.AuxiliaryTypeName + "()).Create()",
            MemberGenerationKind.Primitive =>
                BuildPrimitiveExpr(member),
            _ =>
                $"/* unsupported type: {member.TypeFullName} */",
        };
    }

    private static string BuildPrimitiveExpr(MemberModel m)
    {
        bool hasBounds = m.RangeMin.HasValue && m.RangeMax.HasValue;
        bool hasStrLen = m.StringMinLength.HasValue || m.StringMaxLength.HasValue;

        if (hasBounds)
        {
            double min = m.RangeMin!.Value;
            double max = m.RangeMax!.Value;

            string expr = m.TypeFullName switch
            {
                "System.Int32" => $"global::Conjecture.Core.Generate.Integers<int>({(int)min}, {(int)max})",
                "System.Int64" => $"global::Conjecture.Core.Generate.Integers<long>({(long)min}, {(long)max})",
                "System.Int16" => $"global::Conjecture.Core.Generate.Integers<short>({(short)min}, {(short)max})",
                "System.Byte" => $"global::Conjecture.Core.Generate.Integers<byte>({(byte)min}, {(byte)max})",
                "System.UInt32" => $"global::Conjecture.Core.Generate.Integers<uint>({(uint)min}, {(uint)max})",
                "System.UInt64" => $"global::Conjecture.Core.Generate.Integers<ulong>({(ulong)min}, {(ulong)max})",
                "System.UInt16" => $"global::Conjecture.Core.Generate.Integers<ushort>({(ushort)min}, {(ushort)max})",
                "System.SByte" => $"global::Conjecture.Core.Generate.Integers<sbyte>({(sbyte)min}, {(sbyte)max})",
                "System.Double" => $"global::Conjecture.Core.Generate.Doubles({min.ToString("R", CultureInfo.InvariantCulture)}D, {max.ToString("R", CultureInfo.InvariantCulture)}D)",
                "System.Single" => $"global::Conjecture.Core.Generate.Floats({((float)min).ToString("R", CultureInfo.InvariantCulture)}F, {((float)max).ToString("R", CultureInfo.InvariantCulture)}F)",
                "System.Decimal" => $"global::Conjecture.Core.Generate.Decimals({((decimal)min).ToString("G", CultureInfo.InvariantCulture)}m, {((decimal)max).ToString("G", CultureInfo.InvariantCulture)}m)",
                _ => string.Empty,
            };

            if (!string.IsNullOrEmpty(expr))
            {
                return expr;
            }
        }

        if (hasStrLen && m.TypeFullName == "System.String")
        {
            int minLen = m.StringMinLength ?? 0;
            int maxLen = m.StringMaxLength ?? 20;
            return $"global::Conjecture.Core.Generate.Strings(minLength: {minLen}, maxLength: {maxLen})";
        }

        return PrimitiveData.TryGetValue(m.TypeFullName, out (string GenExpr, string ShortName) d)
            ? d.GenExpr
            : $"/* unsupported type: {m.TypeFullName} */";
    }

    private static string BuildWrappedExpr(string innerFqn, string wrapper)
    {
        return PrimitiveData.TryGetValue(innerFqn, out (string GenExpr, string ShortName) data)
            ? "global::Conjecture.Core.Generate." + wrapper + "(" + data.GenExpr + ")"
            : $"/* unsupported {wrapper} inner type: {innerFqn} */";
    }

    private static string BuildDictionaryStrategyType(string aux)
    {
        int pipe = aux.IndexOf('|');
        if (pipe < 0)
        {
            return "/* unsupported */";
        }

        string keyFqn = aux.Substring(0, pipe);
        string valFqn = aux.Substring(pipe + 1);
        string keyShort = PrimitiveData.TryGetValue(keyFqn, out (string GenExpr, string ShortName) k) ? k.ShortName : "/* unsupported */";
        string valShort = PrimitiveData.TryGetValue(valFqn, out (string GenExpr, string ShortName) v) ? v.ShortName : "/* unsupported */";
        return "global::System.Collections.Generic.IReadOnlyDictionary<" + keyShort + ", " + valShort + ">";
    }

    private static string BuildDictionaryGenExpr(string aux)
    {
        int pipe = aux.IndexOf('|');
        if (pipe < 0)
        {
            return "/* unsupported */";
        }

        string keyFqn = aux.Substring(0, pipe);
        string valFqn = aux.Substring(pipe + 1);
        string keyExpr = PrimitiveData.TryGetValue(keyFqn, out (string GenExpr, string ShortName) k) ? k.GenExpr : "/* unsupported */";
        string valExpr = PrimitiveData.TryGetValue(valFqn, out (string GenExpr, string ShortName) v) ? v.GenExpr : "/* unsupported */";
        return "global::Conjecture.Core.Generate.Dictionaries(" + keyExpr + ", " + valExpr + ")";
    }

    private static string BuildValueTupleStrategyType(string aux)
    {
        string[] parts = aux.Split('|');
        StringBuilder sb = new("(");
        for (int i = 0; i < parts.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(PrimitiveData.TryGetValue(parts[i], out (string GenExpr, string ShortName) p) ? p.ShortName : "/* unsupported */");
        }

        sb.Append(')');
        return sb.ToString();
    }

    private static string BuildValueTupleGenExpr(string aux)
    {
        string[] parts = aux.Split('|');
        StringBuilder sb = new("global::Conjecture.Core.Generate.Tuples(");
        for (int i = 0; i < parts.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(PrimitiveData.TryGetValue(parts[i], out (string GenExpr, string ShortName) p) ? p.GenExpr : "/* unsupported */");
        }

        sb.Append(')');
        return sb.ToString();
    }
}