// Copyright (c) 2026 Kim Ommundsen. Licensed under the MPL-2.0.
// See LICENSE.txt in the project root or https://mozilla.org/MPL/2.0/

using System.Collections.Generic;
using System.Text;

namespace Conjecture.Generators;

internal static class StrategyEmitter
{
    private static readonly Dictionary<string, (string GenExpr, string ShortName)> PrimitiveData = new()
    {
        ["System.Int32"] = ("global::Conjecture.Core.Generate.Integers<int>()", "int"),
        ["System.Int64"] = ("global::Conjecture.Core.Generate.Integers<long>()", "long"),
        ["System.Byte"] = ("global::Conjecture.Core.Generate.Integers<byte>()", "byte"),
        ["System.Boolean"] = ("global::Conjecture.Core.Generate.Booleans()", "bool"),
        ["System.String"] = ("global::Conjecture.Core.Generate.Strings()", "string"),
        ["System.Double"] = ("global::Conjecture.Core.Generate.Doubles()", "double"),
        ["System.Single"] = ("global::Conjecture.Core.Generate.Floats()", "float"),
        ["System.Decimal"] = ("global::Conjecture.Core.Generate.Just(default(decimal))", "decimal"),
        ["System.Guid"] = ("global::Conjecture.Core.Generate.Just(default(global::System.Guid))", "global::System.Guid"),
        ["System.UInt32"] = ("global::Conjecture.Core.Generate.Integers<uint>()", "uint"),
        ["System.UInt64"] = ("global::Conjecture.Core.Generate.Integers<ulong>()", "ulong"),
        ["System.Int16"] = ("global::Conjecture.Core.Generate.Integers<short>()", "short"),
        ["System.UInt16"] = ("global::Conjecture.Core.Generate.Integers<ushort>()", "ushort"),
        ["System.SByte"] = ("global::Conjecture.Core.Generate.Integers<sbyte>()", "sbyte"),
    };

    internal static string Emit(TypeModel model)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine("namespace " + model.Namespace + ";");
            sb.AppendLine();
        }

        string fqn = model.FullyQualifiedName;
        string className = model.TypeName + "Arbitrary";

        sb.AppendLine("internal sealed class " + className + " : global::Conjecture.Core.IStrategyProvider<" + fqn + ">");
        sb.AppendLine("{");

        bool isPartialCtor = model.ConstructionMode == ConstructionMode.PartialConstructor;
        string fieldVisibility = isPartialCtor ? "internal" : "private";

        if (!model.Members.IsEmpty)
        {
            for (int i = 0; i < model.Members.Length; i++)
            {
                MemberModel member = model.Members[i];
                sb.AppendLine("    " + fieldVisibility + " static readonly global::Conjecture.Core.Strategy<" + ResolveStrategyType(member) + "> _s" + i + " = " + ResolveGenExpr(member) + ";");
            }
            sb.AppendLine();
        }

        if (isPartialCtor)
        {
            sb.AppendLine("    public global::Conjecture.Core.Strategy<" + fqn + "> Create()");
            sb.AppendLine("    {");
            sb.AppendLine("        return global::Conjecture.Core.Generate.Compose<" + fqn + ">(ctx =>");
            sb.AppendLine("        {");
            sb.AppendLine("            using global::System.IDisposable _scope = global::Conjecture.Core.PartialConstructorContext.Use(ctx);");
            sb.AppendLine("            return new " + fqn + "();");
            sb.AppendLine("        });");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine("    public global::Conjecture.Core.Strategy<" + fqn + "> Create() =>");

            if (model.Members.IsEmpty)
            {
                sb.AppendLine("        global::Conjecture.Core.Generate.Compose<" + fqn + ">(_ => new " + fqn + "());");
            }
            else if (model.ConstructionMode == ConstructionMode.ObjectInitializer)
            {
                sb.AppendLine("        global::Conjecture.Core.Generate.Compose<" + fqn + ">(ctx => new " + fqn + " {");

                for (int i = 0; i < model.Members.Length; i++)
                {
                    MemberModel member = model.Members[i];
                    bool isLast = i == model.Members.Length - 1;
                    string suffix = isLast ? " });" : ",";
                    sb.AppendLine("            " + member.Name + " = ctx.Generate(_s" + i + ")" + suffix);
                }
            }
            else
            {
                sb.AppendLine("        global::Conjecture.Core.Generate.Compose<" + fqn + ">(ctx => new " + fqn + "(");

                for (int i = 0; i < model.Members.Length; i++)
                {
                    bool isLast = i == model.Members.Length - 1;
                    string suffix = isLast ? "));" : ",";
                    sb.AppendLine("            ctx.Generate(_s" + i + ")" + suffix);
                }
            }

        }

        sb.AppendLine("}");

        if (isPartialCtor && !model.Members.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine("partial class " + model.TypeName);
            sb.AppendLine("{");
            sb.AppendLine("    public partial " + model.TypeName + "()");
            sb.AppendLine("    {");

            for (int i = 0; i < model.Members.Length; i++)
            {
                MemberModel member = model.Members[i];
                sb.AppendLine("        " + member.Name + " = global::Conjecture.Core.PartialConstructorContext.Current.Generate(" + className + "._s" + i + ");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    internal static string ResolveStrategyType(MemberModel member) => member.Kind switch
    {
        MemberGenerationKind.Primitive =>
            PrimitiveData.TryGetValue(member.TypeFullName, out (string GenExpr, string ShortName) p) ? p.ShortName : "/* unsupported */",
        MemberGenerationKind.Enum =>
            "global::" + member.TypeFullName,
        MemberGenerationKind.NullableValue =>
            PrimitiveData.TryGetValue(member.AuxiliaryTypeName, out (string GenExpr, string ShortName) n) ? n.ShortName + "?" : "/* unsupported */",
        MemberGenerationKind.List =>
            PrimitiveData.TryGetValue(member.AuxiliaryTypeName, out (string GenExpr, string ShortName) l)
                ? "global::System.Collections.Generic.List<" + l.ShortName + ">"
                : "/* unsupported */",
        MemberGenerationKind.ArbitraryReference =>
            "global::" + member.TypeFullName,
        MemberGenerationKind.ExternalStrategyProvider =>
            "global::" + member.TypeFullName,
        _ =>
            "/* unsupported */",
    };

    internal static string ResolveGenExpr(MemberModel member)
    {
        return member.Kind switch
        {
            MemberGenerationKind.Enum =>
                "global::Conjecture.Core.Generate.Enums<global::" + member.TypeFullName + ">()",
            MemberGenerationKind.NullableValue =>
                BuildWrappedExpr(member.AuxiliaryTypeName, "Nullable"),
            MemberGenerationKind.List =>
                BuildWrappedExpr(member.AuxiliaryTypeName, "Lists"),
            MemberGenerationKind.ArbitraryReference =>
                "new global::" + member.TypeFullName + "Arbitrary().Create()",
            MemberGenerationKind.ExternalStrategyProvider =>
                "((global::Conjecture.Core.IStrategyProvider<global::" + member.TypeFullName + ">)new global::" + member.AuxiliaryTypeName + "()).Create()",
            MemberGenerationKind.Primitive =>
                PrimitiveData.TryGetValue(member.TypeFullName, out (string GenExpr, string ShortName) d) ? d.GenExpr : $"/* unsupported type: {member.TypeFullName} */",
            _ =>
                $"/* unsupported type: {member.TypeFullName} */",
        };
    }

    private static string BuildWrappedExpr(string innerFqn, string wrapper)
    {
        return PrimitiveData.TryGetValue(innerFqn, out (string GenExpr, string ShortName) data)
            ? "global::Conjecture.Core.Generate." + wrapper + "<" + data.ShortName + ">(" + data.GenExpr + ")"
            : $"/* unsupported {wrapper} inner type: {innerFqn} */";
    }
}