namespace Conjecture.Core;

/// <summary>
/// Specifies that a property-based test parameter should be generated by invoking
/// a named static factory method on the test class.
/// </summary>
/// <param name="methodName">
/// The name of a static method on the test class that returns <c>Strategy&lt;T&gt;</c>.
/// </param>
[AttributeUsage(AttributeTargets.Parameter)]
public sealed class FromFactoryAttribute(string methodName) : Attribute
{
    /// <summary>The name of the static factory method to invoke.</summary>
    public string MethodName => methodName;
}
