// Copyright (c) 2026 Kim Ommundsen. Licensed under the MPL-2.0.
// See LICENSE.txt in the project root or https://mozilla.org/MPL/2.0/

namespace Conjecture.Core;

/// <summary>
/// Specifies that a property-based test parameter should be generated by invoking
/// a named static method on the test class.
/// </summary>
/// <param name="methodName">
/// The name of a static method on the test class that returns <c>Strategy&lt;T&gt;</c>.
/// </param>
[AttributeUsage(AttributeTargets.Parameter)]
public sealed class FromMethodAttribute(string methodName) : Attribute
{
    /// <summary>The name of the static method to invoke.</summary>
    public string MethodName => methodName;
}